package org.powbot.krulvis.api.extensions.items

import org.powbot.api.rt4.Varpbits

enum class GiantsFoundryItem(val parentBar: GiantsFoundryItem?, override val ids: IntArray, val barCount: Int = 1) : Item {
    BRONZE_BAR(null, intArrayOf(Bar.BRONZE.id)),
    BRONZE_PLATEBODY(BRONZE_BAR, intArrayOf(Item.BRONZE_PLATEBODY), 4),
    BRONZE_WARHAMMER(BRONZE_BAR, intArrayOf(Item.BRONZE_WARHAMMER), 2),
    BRONZE_BATTLEAXE(BRONZE_BAR, intArrayOf(Item.BRONZE_BATTLEAXE), 2),
    BRONZE_CHAINBODY(BRONZE_BAR, intArrayOf(Item.BRONZE_CHAINBODY), 2),
    BRONZE_KITESHIELD(BRONZE_BAR, intArrayOf(Item.BRONZE_KITESHIELD), 2),
    BRONZE_2HSWORD(BRONZE_BAR, intArrayOf(Item.BRONZE_2HSWORD), 2),
    BRONZE_PLATELEGS(BRONZE_BAR, intArrayOf(Item.BRONZE_PLATELEGS), 2),
    BRONZE_PLATESKIRT(BRONZE_BAR, intArrayOf(Item.BRONZE_PLATESKIRT), 2),
    BRONZE_SCIMITAR(BRONZE_BAR, intArrayOf(Item.BRONZE_SCIMITAR)),
    BRONZE_LONGSWORD(BRONZE_BAR, intArrayOf(Item.BRONZE_LONGSWORD)),
    BRONZE_FULLHELM(BRONZE_BAR, intArrayOf(Item.BRONZE_FULLHELM)),
    BRONZE_SQSHIELD(BRONZE_BAR, intArrayOf(Item.BRONZE_SQSHIELD)),
    BRONZE_CLAWS(BRONZE_BAR, intArrayOf(Item.BRONZE_CLAWS)),

    IRON_BAR(null, intArrayOf(Bar.IRON.id)),
    IRON_PLATEBODY(IRON_BAR, intArrayOf(Item.IRON_PLATEBODY), 4),
    IRON_WARHAMMER(IRON_BAR, intArrayOf(Item.IRON_WARHAMMER), 2),
    IRON_BATTLEAXE(IRON_BAR, intArrayOf(Item.IRON_BATTLEAXE), 2),
    IRON_CHAINBODY(IRON_BAR, intArrayOf(Item.IRON_CHAINBODY), 2),
    IRON_KITESHIELD(IRON_BAR, intArrayOf(Item.IRON_KITESHIELD), 2),
    IRON_2HSWORD(IRON_BAR, intArrayOf(Item.IRON_2HSWORD), 2),
    IRON_PLATELEGS(IRON_BAR, intArrayOf(Item.IRON_PLATELEGS), 2),
    IRON_PLATESKIRT(IRON_BAR, intArrayOf(Item.IRON_PLATESKIRT), 2),
    IRON_SCIMITAR(IRON_BAR, intArrayOf(Item.IRON_SCIMITAR)),
    IRON_LONGSWORD(IRON_BAR, intArrayOf(Item.IRON_LONGSWORD)),
    IRON_FULLHELM(IRON_BAR, intArrayOf(Item.IRON_FULLHELM)),
    IRON_SQSHIELD(IRON_BAR, intArrayOf(Item.IRON_SQSHIELD)),
    IRON_CLAWS(IRON_BAR, intArrayOf(Item.IRON_CLAWS)),

    STEEL_BAR(null, intArrayOf(Bar.STEEL.id)),
    STEEL_PLATEBODY(STEEL_BAR, intArrayOf(Item.STEEL_PLATEBODY), 4),
    STEEL_WARHAMMER(STEEL_BAR, intArrayOf(Item.STEEL_WARHAMMER), 2),
    STEEL_BATTLEAXE(STEEL_BAR, intArrayOf(Item.STEEL_BATTLEAXE), 2),
    STEEL_CHAINBODY(STEEL_BAR, intArrayOf(Item.STEEL_CHAINBODY), 2),
    STEEL_KITESHIELD(STEEL_BAR, intArrayOf(Item.STEEL_KITESHIELD), 2),
    STEEL_2HSWORD(STEEL_BAR, intArrayOf(Item.STEEL_2HSWORD), 2),
    STEEL_PLATELEGS(STEEL_BAR, intArrayOf(Item.STEEL_PLATELEGS), 2),
    STEEL_PLATESKIRT(STEEL_BAR, intArrayOf(Item.STEEL_PLATESKIRT), 2),
    STEEL_SCIMITAR(STEEL_BAR, intArrayOf(Item.STEEL_SCIMITAR)),
    STEEL_LONGSWORD(STEEL_BAR, intArrayOf(Item.STEEL_LONGSWORD)),
    STEEL_FULLHELM(STEEL_BAR, intArrayOf(Item.STEEL_FULLHELM)),
    STEEL_SQSHIELD(STEEL_BAR, intArrayOf(Item.STEEL_SQSHIELD)),
    STEEL_CLAWS(STEEL_BAR, intArrayOf(Item.STEEL_CLAWS)),

    MITHRIL_BAR(null, intArrayOf(Bar.MITHRIL.id)),
    MITHRIL_PLATEBODY(MITHRIL_BAR, intArrayOf(Item.MITHRIL_PLATEBODY), 4),
    MITHRIL_WARHAMMER(MITHRIL_BAR, intArrayOf(Item.MITHRIL_WARHAMMER), 2),
    MITHRIL_BATTLEAXE(MITHRIL_BAR, intArrayOf(Item.MITHRIL_BATTLEAXE), 2),
    MITHRIL_CHAINBODY(MITHRIL_BAR, intArrayOf(Item.MITHRIL_CHAINBODY), 2),
    MITHRIL_KITESHIELD(MITHRIL_BAR, intArrayOf(Item.MITHRIL_KITESHIELD), 2),
    MITHRIL_2HSWORD(MITHRIL_BAR, intArrayOf(Item.MITHRIL_2HSWORD), 2),
    MITHRIL_PLATELEGS(MITHRIL_BAR, intArrayOf(Item.MITHRIL_PLATELEGS), 2),
    MITHRIL_PLATESKIRT(MITHRIL_BAR, intArrayOf(Item.MITHRIL_PLATESKIRT), 2),
    MITHRIL_SCIMITAR(MITHRIL_BAR, intArrayOf(Item.MITHRIL_SCIMITAR)),
    MITHRIL_LONGSWORD(MITHRIL_BAR, intArrayOf(Item.MITHRIL_LONGSWORD)),
    MITHRIL_FULLHELM(MITHRIL_BAR, intArrayOf(Item.MITHRIL_FULLHELM)),
    MITHRIL_SQSHIELD(MITHRIL_BAR, intArrayOf(Item.MITHRIL_SQSHIELD)),
    MITHRIL_CLAWS(MITHRIL_BAR, intArrayOf(Item.MITHRIL_CLAWS)),

    ADAMANTITE_BAR(null, intArrayOf(Bar.ADAMANTITE.id)),
    ADAMANT_PLATEBODY(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_PLATEBODY), 4),
    ADAMANT_WARHAMMER(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_WARHAMMER), 2),
    ADAMANT_BATTLEAXE(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_BATTLEAXE), 2),
    ADAMANT_CHAINBODY(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_CHAINBODY), 2),
    ADAMANT_KITESHIELD(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_KITESHIELD), 2),
    ADAMANT_2HSWORD(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_2HSWORD), 2),
    ADAMANT_PLATELEGS(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_PLATELEGS), 2),
    ADAMANT_PLATESKIRT(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_PLATESKIRT), 2),
    ADAMANT_SCIMITAR(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_SCIMITAR)),
    ADAMANT_LONGSWORD(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_LONGSWORD)),
    ADAMANT_FULLHELM(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_FULLHELM)),
    ADAMANT_SQSHIELD(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_SQSHIELD)),
    ADAMANT_CLAWS(ADAMANTITE_BAR, intArrayOf(Item.ADAMANT_CLAWS)),

    RUNITE_BAR(null, intArrayOf(Bar.RUNITE.id)),
    RUNITE_PLATEBODY(RUNITE_BAR, intArrayOf(Item.RUNE_PLATEBODY), 4),
    RUNITE_WARHAMMER(RUNITE_BAR, intArrayOf(Item.RUNE_WARHAMMER), 2),
    RUNITE_BATTLEAXE(RUNITE_BAR, intArrayOf(Item.RUNE_BATTLEAXE), 2),
    RUNITE_CHAINBODY(RUNITE_BAR, intArrayOf(Item.RUNE_CHAINBODY), 2),
    RUNITE_KITESHIELD(RUNITE_BAR, intArrayOf(Item.RUNE_KITESHIELD), 2),
    RUNITE_2HSWORD(RUNITE_BAR, intArrayOf(Item.RUNE_2HSWORD), 2),
    RUNITE_PLATELEGS(RUNITE_BAR, intArrayOf(Item.RUNE_PLATELEGS), 2),
    RUNITE_PLATESKIRT(RUNITE_BAR, intArrayOf(Item.RUNE_PLATESKIRT), 2),
    RUNITE_SCIMITAR(RUNITE_BAR, intArrayOf(Item.RUNE_SCIMITAR)),
    RUNITE_LONGSWORD(RUNITE_BAR, intArrayOf(Item.RUNE_LONGSWORD)),
    RUNITE_FULLHELM(RUNITE_BAR, intArrayOf(Item.RUNE_FULLHELM)),
    RUNITE_SQSHIELD(RUNITE_BAR, intArrayOf(Item.RUNE_SQSHIELD)),
    RUNITE_CLAWS(RUNITE_BAR, intArrayOf(Item.RUNE_CLAWS));

    val giantsFoundryCount: Int
        get() = Varpbits.varpbit(GIANTS_FOUNDRY_VARP, 5 * METAL_BARS.indexOf(this), 31)

    override fun hasWith(): Boolean {
        return getCount(false) >= 1
    }

    override fun getCount(countNoted: Boolean): Int {
        return getInventoryCount(countNoted)
    }

    companion object {
        val METAL_BARS = arrayOf(BRONZE_BAR, IRON_BAR, STEEL_BAR, MITHRIL_BAR, ADAMANTITE_BAR, RUNITE_BAR)
        val GIANTS_FOUNDRY_VARP = 3431

        fun forId(id: Int) = values().firstOrNull { it.id == id }
    }
}